version: "3.8"

services:
  backend:
    build: .
    container_name: ahomApp
    ports:
      - 5000:5000
    env_file:
      - ./src/.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: ahomDB
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
